import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'PlayStation 5',
    description: 'Next-gen gaming console from Sony.',
    price: 499.99,
    category: 'Consoles',
    platform: 'PlayStation',
    imageId: 'ps5-console',
    rating: 5,
  },
  {
    id: '2',
    name: 'Xbox Series X',
    description: 'The most powerful Xbox ever.',
    price: 499.99,
    category: 'Consoles',
    platform: 'Xbox',
    imageId: 'xbox-series-x',
    rating: 4,
  },
  {
    id: '3',
    name: 'Nintendo Switch OLED',
    description: 'Handheld-home console hybrid with a vibrant OLED screen.',
    price: 349.99,
    category: 'Consoles',
    platform: 'Nintendo',
    imageId: 'nintendo-switch',
    rating: 5,
  },
  {
    id: '4',
    name: 'Cyberpunk 2077',
    description: 'An open-world, action-adventure story set in Night City.',
    price: 59.99,
    category: 'Games',
    platform: 'PlayStation',
    imageId: 'cyberpunk-2077-ps5',
    rating: 4,
  },
  {
    id: '5',
    name: 'Halo Infinite',
    description: 'The legendary Halo series returns.',
    price: 59.99,
    category: 'Games',
    platform: 'Xbox',
    imageId: 'halo-infinite-xbox',
    rating: 4,
  },
  {
    id: '6',
    name: 'The Legend of Zelda: Breath of the Wild',
    description: 'Step into a world of discovery, exploration, and adventure.',
    price: 59.99,
    category: 'Games',
    platform: 'Nintendo',
    imageId: 'zelda-botw-switch',
    rating: 5,
  },
  {
    id: '7',
    name: 'Elden Ring',
    description: 'A fantasy action-RPG adventure set within a world created by Hidetaka Miyazaki and George R. R. Martin.',
    price: 59.99,
    category: 'Games',
    platform: 'PC',
    imageId: 'elden-ring-pc',
    rating: 5,
  },
  {
    id: '8',
    name: 'Hogwarts Legacy',
    description: 'Live the unwritten in the 1800s wizarding world.',
    price: 69.99,
    category: 'Games',
    platform: 'PlayStation',
    imageId: 'hogwarts-legacy-ps5',
    rating: 4,
  },
   {
    id: '9',
    name: "Marvel's Spider-Man 2",
    description: 'An all-new adventure in the Marvel\'s Spider-Man universe.',
    price: 69.99,
    category: 'Games',
    platform: 'PlayStation',
    imageId: 'spiderman-2-ps5',
    rating: 5,
  },
  {
    id: '10',
    name: 'Geek Haven T-Shirt',
    description: 'Official Geek Haven logo t-shirt. 100% cotton.',
    price: 24.99,
    category: 'Merchandise',
    imageId: 'geek-tshirt',
    rating: 5,
  },
  {
    id: '11',
    name: 'Funko Pop! Figure',
    description: 'Collectible vinyl figure from your favorite fandom.',
    price: 12.99,
    category: 'Merchandise',
    imageId: 'funkopop-figure',
    rating: 4,
  },
  {
    id: '12',
    name: 'RGB Gaming Mouse',
    description: 'High-DPI gaming mouse with customizable RGB lighting.',
    price: 49.99,
    category: 'Merchandise',
    imageId: 'gaming-mouse',
    rating: 4,
  },
  {
    id: '13',
    name: 'Mechanical Keyboard',
    description: 'Clicky and responsive mechanical keyboard for gaming and typing.',
    price: 119.99,
    category: 'Merchandise',
    imageId: 'mechanical-keyboard',
    rating: 5,
  },
  {
    id: '14',
    name: 'Wireless Gaming Headset',
    description: 'Immersive sound and a crystal-clear microphone.',
    price: 149.99,
    category: 'Merchandise',
    imageId: 'gaming-headset',
    rating: 5,
  },
  {
    id: '15',
    name: 'Animal Crossing: New Horizons',
    description: 'Escape to a deserted island and create your own paradise.',
    price: 59.99,
    category: 'Games',
    platform: 'Nintendo',
    imageId: 'animal-crossing-switch',
    rating: 5,
  },
  {
    id: '16',
    name: 'Stardew Valley',
    description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.',
    price: 14.99,
    category: 'Games',
    platform: 'PC',
    imageId: 'stardew-valley-pc',
    rating: 5,
  }
];
